# Generated by Django 5.2.7 on 2025-11-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfoliouser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='PortfolioUser',
        ),
    ]
