# Generated by Django 5.2.7 on 2025-11-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_media_user_remove_portfoliouser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin'), ('SUPERADMIN', 'superadmin')], default='USER', max_length=20),
        ),
    ]
