# Generated by Django 5.2.7 on 2025-11-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
